name = "cloud-region-explorer-api"
main = "index.ts"
compatibility_date = "2026-07-16"

[[d1_databases]]
binding = "CLOUD_REGIONS_DB"
database_name = "cloud-regions-db"
database_id = ""

[triggers]
crons = ["0 0 * * *"]